name: "build"

on: [pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
          clean: true

      - name: Clean checkout
        run: |
          for tag in `git tag -l`; do git tag -d $tag; done
          git fetch && git fetch -t && git checkout ${{github.head_ref}}

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Config"
        run: |
          git config --global user.email "git-ci@techinity.com"
          git config --global user.name "gitci"

      - name: "Install dependencies"
        run: npm install

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run test

      - name: "Commit build output"
        run: |
          git checkout -B "dist/artifacts-${{github.event.number}}"
          git reset ${{github.event.after}}
          git add -f dist/
          git commit -m "ci: build distributables" || true
          git push -f https://${{secrets.GH_ACTION_TOKEN}}@github.com/allenevans/short-sha.git HEAD:dist/artifacts-${{github.event.number}}

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed filces after build." \
              && exit 1)
